name: prebuild
on:
  push:
    branches:
      - main
jobs:
  linux:
    name: Prebuild Binaries for Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Setup Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-multilib gcc-multilib libcups2-dev libcups2-dev:i386 libc6-dev-i386 linux-libc-dev linux-libc-dev:i386
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - uses: actions/checkout@v3
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- -t 15.3.5 -r electron --arch ia32 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 15.3.5 -r electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 22.3.27 -r electron --arch ia32 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 22.3.27 -r electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 32.2.5 -r electron --arch ia32 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 32.2.5 -r electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 20.18.0 -r node --arch ia32 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 20.18.0 -r node --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
  macos:
    name: Prebuild Binaries for macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - uses: actions/checkout@v3
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- -t 15.3.5 -r electron --arch arm64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 22.3.27 -r electron --arch arm64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 32.2.5 -r electron --arch arm64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 20.18.0 -r node --arch arm64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 22.15.0 -r node --arch arm64 -u ${{ secrets.PREBUILD_TOKEN }}
  macos-x64:
    name: Prebuild Binaries for macOS (x64)
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - uses: actions/checkout@v3
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- -t 15.3.5 -r electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 22.3.27 -r electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 32.2.5 -r electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 20.18.0 -r node --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 22.15.0 -r node --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
  windows:
    name: Prebuild Binaries for Windows
    runs-on: windows-2019
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - uses: actions/checkout@v3
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- -t 15.3.5 -r electron --arch ia32 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 15.3.5 -r electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 22.3.27 -r electron --arch ia32 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 22.3.27 -r electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 32.2.5 -r electron --arch ia32 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 32.2.5 -r electron --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 20.18.0 -r node --arch ia32 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 20.18.0 -r node --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
          npm run prebuild -- -t 22.15.0 -r node --arch x64 -u ${{ secrets.PREBUILD_TOKEN }}
